---
ci:
  autofix_commit_msg: |
    Chore: pre-commit autofixes

    Signed-off-by: pre-commit-ci[bot] <pre-commit-ci@users.noreply.github.com>
  autoupdate_commit_msg: |
    Chore: pre-commit autoupdate

    Signed-off-by: pre-commit-ci[bot] <pre-commit-ci@users.noreply.github.com>
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args:
          - --branch=main

  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98 # frozen: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7  # frozen: v1.37.1
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: c8fd5003603dd6f12447314ecd935ba87c09aff5  # frozen: v0.46.0
    hooks:
      - id: markdownlint
        args: ["--fix"]

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: 381d5e68de9fe958938da811f2e094a8f90e8195  # frozen: v1.7.9.24
    hooks:
      - id: actionlint
