---
# SPDX-License-Identifier: MIT
#
# Original code from:
# https://gist.github.com/sbyx/1f6f434f0903b872b84c4302637d0890
blueprint:
  name: Low battery level notification for all battery sensors (v1.3)
  description: v1.2 Regularly test all sensors with 'battery' device-class for
    crossing a certain battery level threshold and if so execute an action.
  domain: automation
  input:
    threshold:
      name: Battery warning level threshold
      description: Battery sensors below threshold are assumed to be
        low-battery (as well as binary battery sensors with value 'on').
      default: 20
      selector:
        number:
          min: 5.0
          max: 100.0
          unit_of_measurement: "%"
          mode: slider
          step: 5.0
    time:
      name: Time to test on
      description: Test is run at configured time
      default: "10:00:00"
      selector:
        time: {}
    days:
      name: (Required) Days to run test
      description: >
        Days of the week when the automation is active.
      selector:
        select:
          options:
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
            - Saturday
            - Sunday
          mode: list
          multiple: true
          sort: false
          custom_value: true
          default:
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
            - Saturday
            - Sunday
    exclude:
      name: Excluded Sensors
      description: Battery sensors (e.g. smartphone) to exclude from detection.
        Only entities are supported, devices must be expanded!
      # yamllint disable rule:braces
      default: { entity_id: [] }
      # yamllint enable rule:braces
      selector:
        target:
          entity:
            device_class: battery
    actions:
      name: Actions
      description: Notifications or similar to be run. {{sensors}} is replaced
        with the names of sensors being low on battery.
      selector:
        action: {}
  # yamllint disable-line rule:line-length
  source_url: https://raw.githubusercontent.com/tykeal/homeassistant-blueprints/main/low-battery.yaml
variables:
  day: !input "day"
  threshold: !input "threshold"
  exclude: !input "exclude"
  # yamllint disable rule:line-length
  sensors: >-
    {%- set result = namespace(sensors=[]) -%}
    {%- for state in states.sensor | selectattr('attributes.device_class', '==', 'battery') -%}
      {%- if 0 <= state.state | int(-1) < threshold | int and not state.entity_id in exclude.entity_id -%}
        {%- set result.sensors = result.sensors + [state.name ~ ' (' ~ state.state ~ ' %)'] -%}
      {%- endif -%}
    {%- endfor -%}
    {%- for state in states.binary_sensor | selectattr('attributes.device_class', '==', 'battery') | selectattr('state', '==', 'on') -%}
      {%- if not state.entity_id in exclude.entity_id -%}
        {%- set result.sensors = result.sensors + [state.name] -%}
      {%- endif -%}
    {%- endfor -%}
    {{result.sensors|join(', ')}}
  # yamlline enable
trigger:
  - platform: time
    at: !input "time"
condition:
  - "{{ sensors != '' and now().strftime('%A') in days }}"
action:
  - choose: []
    default: !input "actions"
mode: single
